package com.krishna.burpagent.launcher;

import com.krishna.burpagent.model.TargetScope;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.LinkedHashMap;
import java.util.Map;

public final class AgentConfiguration {
    private final Path projectRoot;
    private final Map<String, String> values;

    private AgentConfiguration(Path projectRoot, Map<String, String> values) {
        this.projectRoot = projectRoot;
        this.values = Map.copyOf(values);
    }

    public static AgentConfiguration load(Path projectRoot) throws IOException {
        Path normalizedRoot = projectRoot.toAbsolutePath().normalize();
        Map<String, String> values = new LinkedHashMap<>();
        Path envFile = normalizedRoot.resolve(".env");
        if (Files.isRegularFile(envFile)) {
            for (String rawLine : Files.readAllLines(envFile, StandardCharsets.UTF_8)) {
                String line = rawLine.trim();
                if (line.isEmpty() || line.startsWith("#")) continue;
                int separator = line.indexOf('=');
                if (separator <= 0) continue;
                String key = line.substring(0, separator).trim();
                String value = unquote(line.substring(separator + 1).trim());
                values.put(key, value);
            }
        }
        values.putAll(System.getenv());
        return new AgentConfiguration(normalizedRoot, values);
    }

    public Path projectRoot() {
        return projectRoot;
    }

    public Path ofbizSource() {
        return requiredPath("OFBIZ_SOURCE");
    }

    public Path burpExecutable() {
        return Path.of(get("BURP_EXECUTABLE", "/home/krishna/BurpSuite/BurpSuite"))
                .toAbsolutePath().normalize();
    }

    public Path artifactsDirectory() {
        return resolvePath(get("ARTIFACTS_DIR", "artifacts"));
    }

    public String username() {
        return get("OFBIZ_USERNAME", "admin");
    }

    public String password() {
        return get("OFBIZ_PASSWORD", "ofbiz");
    }

    public String targetUrl() {
        return targetScope().url();
    }

    public String targetHost() {
        return targetScope().host();
    }

    public int targetPort() {
        return targetScope().port();
    }

    public String bridgeToken() {
        String token = required("BURP_BRIDGE_TOKEN");
        if (token.length() < 32) {
            throw new IllegalArgumentException("BURP_BRIDGE_TOKEN must contain at least 32 characters");
        }
        return token;
    }

    public int bridgePort() {
        return getInt("BURP_BRIDGE_PORT", 1338);
    }

    public String burpRestApiUrl() {
        return required("BURP_REST_API_URL");
    }

    public String burpRestApiKey() {
        String key = required("BURP_REST_API_KEY");
        if (!key.matches("[A-Za-z0-9_-]{20,}")) {
            throw new IllegalArgumentException(
                    "BURP_REST_API_KEY must be the API key generated by Burp Suite");
        }
        return key;
    }

    public Duration ofbizStartupTimeout() {
        return Duration.ofSeconds(getLong("OFBIZ_STARTUP_SECONDS", 900));
    }

    public Duration bridgeStartupTimeout() {
        return Duration.ofSeconds(getLong("BURP_STARTUP_SECONDS", 300));
    }

    public Duration pollInterval() {
        return Duration.ofSeconds(getLong("SCAN_POLL_SECONDS", 15));
    }

    public Map<String, String> extensionEnvironment(Path runArtifacts) {
        Map<String, String> env = new LinkedHashMap<>();
        env.put("OFBIZ_USERNAME", username());
        env.put("OFBIZ_PASSWORD", password());
        env.put("TARGET_URL", targetUrl());
        env.put("BURP_BRIDGE_TOKEN", bridgeToken());
        env.put("BURP_BRIDGE_PORT", Integer.toString(bridgePort()));
        env.put("ARTIFACTS_DIR", runArtifacts.toString());
        copyIfPresent(env, "SESSION_CHECK_SECONDS");
        return env;
    }

    private TargetScope targetScope() {
        return TargetScope.webTools(get("TARGET_URL", TargetScope.DEFAULT_URL));
    }

    private void copyIfPresent(Map<String, String> destination, String key) {
        String value = values.get(key);
        if (value != null && !value.isBlank()) destination.put(key, value.trim());
    }

    private String required(String key) {
        String value = values.get(key);
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException(key + " is required in .env or the process environment");
        }
        return value.trim();
    }

    private Path requiredPath(String key) {
        Path path = Path.of(required(key)).toAbsolutePath().normalize();
        if (!Files.isDirectory(path)) {
            throw new IllegalArgumentException(key + " is not a directory: " + path);
        }
        return path;
    }

    private Path resolvePath(String value) {
        Path path = Path.of(value);
        return (path.isAbsolute() ? path : projectRoot.resolve(path)).toAbsolutePath().normalize();
    }

    private String get(String key, String defaultValue) {
        String value = values.get(key);
        return value == null || value.isBlank() ? defaultValue : value.trim();
    }

    private int getInt(String key, int defaultValue) {
        return Math.toIntExact(getLong(key, defaultValue));
    }

    private long getLong(String key, long defaultValue) {
        String value = values.get(key);
        if (value == null || value.isBlank()) return defaultValue;
        try {
            return Long.parseLong(value.trim());
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException(key + " must be an integer", e);
        }
    }

    private static String unquote(String value) {
        if (value.length() >= 2) {
            char first = value.charAt(0);
            char last = value.charAt(value.length() - 1);
            if ((first == '"' && last == '"') || (first == '\'' && last == '\'')) {
                return value.substring(1, value.length() - 1);
            }
        }
        return value;
    }
}
